export enum PostAdminSearchCategoryFilter {
    ANNOUNCEMENT_NAME = 'ANNOUNCEMENT_NAME',
    SITE_NAME = 'SITE_NAME',
    REPRESENTATIVE_NAME = 'REPRESENTATIVE_NAME',
    SITE_CONTACT_INFO = 'SITE_CONTACT_INFO',
}
