export enum InquiryAdminGetListInquiryType {
    USE_OF_SERVICES = 'USE_OF_SERVICES',
    ACCOUNT = 'ACCOUNT',
    CAREER = 'CAREER',
    MATCHING = 'MATCHING',
    APPLICATION = 'APPLICATION',
    INTERVIEW = 'INTERVIEW',
    CONTRACT = 'CONTRACT',
    LABOR = 'LABOR',
    WAGE = 'WAGE',
    OTHERS = 'OTHERS',
}
