export enum PostCompanyCheckPullUpStatus {
    FREE_PULL_UP_AVAILABLE = 'FREE_PULL_UP_AVAILABLE',
    PRODUCT_PULL_UP_AVAILABLE = 'PRODUCT_PULL_UP_AVAILABLE',
    PULL_UP_NOT_AVAILABLE = 'PULL_UP_NOT_AVAILABLE',
}
